#!/bin/bash

PORT=/dev/ttyACM0

if [ $1 ]; then
	PORT=$1
fi

python3 ./devwait.py /media/pontus/RPI-RP2/
if [ $? -ne 0 ]; then exit 1; fi
sleep 0.5
echo "Flashing USB to Serial bridge firmware..."
cp ./RP2040USB2Serial.ino.uf2  /media/pontus/RPI-RP2/
sleep 0.5
python3 ./devwait.py $PORT
if [ $? -ne 0 ]; then exit 1; fi
echo "Flashing ESP-NOW AT command firmware to ESP32C3 chip..."
sleep 2
PYTHONPATH=~/bin/esptool python3 ~/bin/esptool/esptool --chip esp32c3 -b 921600 --port $PORT --before default-reset --after hard-reset write-flash --flash-mode dio --flash-size keep --flash-freq 40m 0x0 bin/bootloader.bin 0x8000 bin/partition-table.bin 0x10000 bin/esp_now_at.bin
if [ $? -ne 0 ]; then exit 1; fi
echo "ESP-NOW firmware flashed OK"

